package emp;
// Generated 22 Nov, 2017 9:57:36 AM by Hibernate Tools 4.3.1



/**
 * Emp generated by hbm2java
 */
public class Emp  implements java.io.Serializable {


     private int empid;
     private String ename;
     private Double empsalary;

    public Emp() {
    }

	
    public Emp(int empid) {
        this.empid = empid;
    }
    public Emp(int empid, String ename, Double empsalary) {
       this.empid = empid;
       this.ename = ename;
       this.empsalary = empsalary;
    }
   
    public int getEmpid() {
        return this.empid;
    }
    
    public void setEmpid(int empid) {
        this.empid = empid;
    }
    public String getEname() {
        return this.ename;
    }
    
    public void setEname(String ename) {
        this.ename = ename;
    }
    public Double getEmpsalary() {
        return this.empsalary;
    }
    
    public void setEmpsalary(Double empsalary) {
        this.empsalary = empsalary;
    }




}


